name: SleepOver-HNU

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  # branches:
  #   - master
  schedule:
    - cron: "*/20 17,22 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python # 安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests # 安装requests
      run: |
        pip install requests
    - name: ClockIn # 打卡
      env:
        usr: ${{ secrets.USER }}
        pwd: ${{ secrets.PASSWORD }}
        RealAddress: ${{ secrets.REALADDRESS }}
        RealProvince_City_County: ${{ secrets.REALPROVINCE_CITY_COUNTY }}
        QRCodeColor: ${{ secrets.QRCOdECOLOR }}
      run:
        python AutoClockIn.py $usr $pwd $sckey $RealAddress $RealProvince_City_County $QRCodeColor
